# Constants

## Slack
SLACK_URL=''
SLACK_CHANNEL_ID=''
SLACK_CHANNEL_NAME=''
SLACK_TOKEN=''

## Github
GITHUB_URL=''
GITHUB_REPO=''
GITHUB_TOKEN=''

## Dynamo
DYNAMO_ACCESS_KEY=''
DYNAMO_SECRET_ACCESS_KEY=''
DYNAMO_REGION_NAME=''
DYNAMO_TABLE=''

## Webclient
WEBSERVICE_HOST = ''
WEBSERVICE_RESPONSE = ''
URL = WEBSERVICE_HOST + WEBSERVICE_RESPONSE
